// <auto-generated />
namespace JTMaher.Modules.JTMPasswordsStencilJS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class March2620232 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(March2620232));
        
        string IMigrationMetadata.Id
        {
            get { return "202303270421367_March2620232"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
